version: '3'

services:
  balance_be:
    build:
      context: ./docker/balance_be
    hostname: hostbe
    container_name: cont-balance-java
    ports:
      # puerto-maquina-host:puerto-publico-en-contenedor
      - "8085:8080"
    environment:
      DB_URL: jdbc:mysql://cont-balance-mysql:3306/db_balance?createDatabaseIfNotExist=true&serverTimezone=UTC
      DB_USER_NAME: root
      DB_PASSWORD: 1234
    #volumes:
      #- ../../target/app_balance-0.0.1.jar :/app/app.jar

    # restart: always
    deploy:
      resources:
        limits:
          memory: 512M

    depends_on:
      balance_db:
        condition: service_healthy

  balance_db:
    image: mysql:8.0.33
    hostname: hostmysql
    container_name: cont-balance-mysql
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_PASSWORD: 1234
      MYSQL_DATABASE: db_balance
    # restart: always
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      # timeout: 2s
      # retries: 10
