version: '3'

services:
  balance_java:
    build:
      context: docker/balance_java
    hostname: hostjava
    container_name: cont-balance-java
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:mysql://cont-balance-mysql:3306/db_balance?createDatabaseIfNotExist=true&serverTimezone=UTC
      DB_USER_NAME: root
      DB_PASSWORD: 1234
    # restart: always
    deploy:
      resources:
        limits:
          memory: 512M

    depends_on:
      balance_db:
        condition: service_healthy

  balance_db:
    image: mysql:8.0.33
    hostname: hotsmysql
    container_name: cont-balance-mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_PASSWORD: 1234
      MYSQL_DATABASE: db_balance
    # restart: always
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 10s
      retries: 10